{{- if .Values.modelServer.mlPredictServer.enabled -}}
apiVersion: {{ template "daiops.service.apiVersion" . }}
kind: Service
metadata:
  labels:
    app: {{ template "daiops.metadata.namespace" . }}-{{ .Values.modelServer.mlPredictServer.name }}
  name: {{ template "daiops.metadata.namespace" . }}-{{ .Values.modelServer.mlPredictServer.name }}
  namespace: {{ template "daiops.metadata.namespace" . }}
spec:
  ports:
  - name: predict 
    port: {{ .Values.modelServer.mlPredictServer.service.ports.predict.servicePort }}
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ template "daiops.metadata.namespace" . }}-{{ .Values.modelServer.mlPredictServer.name }}
  type: {{ .Values.modelServer.mlPredictServer.service.type }}
{{- end -}}