{{- if .Values.modelServer.mlProcessServer.enabled -}}
apiVersion: {{ template "daiops.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "daiops.metadata.namespace" . }}-{{ .Values.modelServer.mlProcessServer.name }}
  namespace: {{ template "daiops.metadata.namespace" . }}
  labels:
    app: {{ template "daiops.metadata.namespace" . }}-{{ .Values.modelServer.mlProcessServer.name }}
spec:
  replicas: {{ .Values.modelServer.mlProcessServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "daiops.metadata.namespace" . }}-{{ .Values.modelServer.mlProcessServer.name }}
  template:
    metadata:
      labels:
        app: {{ template "daiops.metadata.namespace" . }}-{{ .Values.modelServer.mlProcessServer.name }}
    spec:
      containers:
      - name: {{ template "daiops.metadata.namespace" . }}-{{ .Values.modelServer.mlProcessServer.name }}
        image: {{ .Values.registry.hostname }}:{{ .Values.registry.port}}/{{ .Values.registry.project }}/{{ .Values.modelServer.mlProcessServer.image.name }}:{{ .Values.modelServer.mlProcessServer.image.tag }}
        imagePullPolicy: {{ .Values.modelServer.mlProcessServer.image.pullPolicy }}
        {{- with .Values.modelServer.mlProcessServer.image.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}  
        {{- with .Values.modelServer.mlProcessServer.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end -}}



